- Has the network latency gone up since we switched internet service providers?

Ho:  the network latency did not change since we switched internet service providers.
Ha:  the network latency has gone up since we switched internet service providers.

True positive: Rejecting the null hypothesis when it's false. Change has been detected.
True negative: Accepting Ho when it's true. Change has not been detected.
Type I: Rejecting the Ho when it's true. Falsely concluded that there is a change while in reality there was not.
Type II: Accepting the Ho when it's False. Falsely concluded there is no change when there is a change.

- Is the website redesign any good?

Ho: webredesign is the same as previous webdesign
Ha: webredeign is better than previous webdesign

True positive: Rejecting the null hypothesis when it's false. Webredesign is better.
True negative: Accepting Ho when it's true. webredisgn is the same.
Type I: Rejecting the Ho when it's true. Falsely concluded that webredesign is better where in reality they are the same.
Type II: Accepting the Ho when it's False. Falsely concluded webredesign is the same where in reality webredisgn is better.

- Is our television ad driving more sales?

Ho: our television ad does not affect sales
Ha: our television ad drives more sales

True positive: Rejecting the null hypothesis when it's false. tele ad drives more sales.
True negative: Accepting Ho when it's true. tele ad does not affect sales
Type I: Rejecting the Ho when it's true. Falsely concluded that tele ad drives more sales when in reality it does not affect the sales.
Type II: Accepting the Ho when it's False. Falsely concluded tele ad does not affect sales when in reality it drives more sales.

# -------------------------- Chi Square exercises ---------------------------- #

# 1. Does using a Macbook and being a Codeup student are independent of each other.

Ho: using a Macbook and being a Codeup student are independent of each other.
Ha: using a Macbook and being a Codeup student are dependent of each other.

In [136]:
import pandas as pd
import numpy as np

from pydataset import data
from scipy import stats

In [132]:
data = {
    'codeup': ['yes', 'no'],
    'mac': [49, 1],
    'notmac':[20,30]
}

df = pd.DataFrame(data)
df = df.set_index('codeup')
df

mac  notmac
codeup             
yes      49      20
no        1      30

In [84]:
alpha = 0.05

In [79]:
chi2,p,degf,expected = stats.chi2_contingency(df)
p

1.4116760526193828e-09

In [82]:
print('df')
print(df.values)
print('\nExpected')
print(expected.astype(int))
print('\n----')
print(f'chi^2 = {chi2:.4f}')
print(f'p     = {p:.4f}')

df
[[49 20]
 [ 1 30]]

Expected
[[34 34]
 [15 15]]

----
chi^2 = 36.6526
p     = 0.0000


In [86]:
if p < alpha:
    print('reject the null hypothesis, using a Macbook and being a Codeup student are dependent of each other. ')
else:
    print('fail to reject the null hypothesis')

reject the null hypothesis, using a Macbook and being a Codeup student are dependent of each other. 


# 2. Choose another 2 categorical variables from the mpg dataset.

In [ ]:
# State your null and alternative hypotheses.
Ho: year has no impact on city mile per gallon
Ha: year has impact on city mile per gallon

In [138]:
mpg = data('mpg')
data('mpg',show_doc =True)
mpg.head(5)


mpg

PyDataset Documentation (adopted from R Documentation. The displayed examples are in R)

## Fuel economy data from 1999 and 2008 for 38 popular models of car

### Description

This dataset contains a subset of the fuel economy data that the EPA makes
available on http://fueleconomy.gov. It contains only models which had a new
release every year between 1999 and 2008 - this was used as a proxy for the
popularity of the car.

### Usage

    data(mpg)

### Format

A data frame with 234 rows and 11 variables

### Details

  * manufacturer. 

  * model. 

  * displ. engine displacement, in litres 

  * year. 

  * cyl. number of cylinders 

  * trans. type of transmission 

  * drv. f = front-wheel drive, r = rear wheel drive, 4 = 4wd 

  * cty. city miles per gallon 

  * hwy. highway miles per gallon 

  * fl. 

  * class. 




manufacturer model  displ  year  cyl       trans drv  cty  hwy fl    class
1         audi    a4    1.8  1999    4    auto(l5)   f   18   29  p  compact
2         audi    a4    1.8  1999    4  manual(m5)   f   21   29  p  compact
3         audi    a4    2.0  2008    4  manual(m6)   f   20   31  p  compact
4         audi    a4    2.0  2008    4    auto(av)   f   21   30  p  compact
5         audi    a4    2.8  1999    6    auto(l5)   f   16   26  p  compact

In [ ]:
# State your alpha.
alpha = 0.05

In [98]:
# Perform a chi square test of independence.
observed = pd.crosstab(mpg.year,mpg.cty)
observed

cty   9   11  12  13  14  15  16  17  18  19  ...  21  22  23  24  25  26  28  \
year                                          ...                               
1999   0  16   0   7   9  16  10   5  21  11  ...  11   0   1   4   1   1   1   
2008   5   4   8  14  10   8   9  11   5   9  ...  12   4   2   1   1   2   1   

cty   29  33  35  
year              
1999   1   1   1  
2008   0   0   0  

[2 rows x 21 columns]

In [100]:
chi2,p,degf,expected = stats.chi2_contingency(observed)

In [101]:
print('Observed')
print(observed.values)
print('\nExpected')
print(expected.astype(int))
print('\n----')
print(f'chi^2 = {chi2:.4f}')
print(f'p     = {p:.4f}')

Observed
[[ 0 16  0  7  9 16 10  5 21 11  0 11  0  1  4  1  1  1  1  1  1]
 [ 5  4  8 14 10  8  9 11  5  9 11 12  4  2  1  1  2  1  0  0  0]]

Expected
[[ 2 10  4 10  9 12  9  8 13 10  5 11  2  1  2  1  1  1  0  0  0]
 [ 2 10  4 10  9 12  9  8 13 10  5 11  2  1  2  1  1  1  0  0  0]]

----
chi^2 = 58.1116
p     = 0.0000


In [103]:
#compare our p-value and alpha
if p < alpha:
    print('reject the null hypothesis, year has impact on city mile per gallon')
else:
    print('fail to reject the null hypothesis')

reject the null hypothesis, year has impact on city mile per gallon


# 3 Use the data from the employees database to answer these questions:

In [106]:
import env
url = f'mysql+pymysql://{env.user}:{env.password}@{env.host}/employees'

In [121]:
query = pd.read_sql(

'''
select dept_manager.emp_no as manager_emp_no, gender, dept_name, employees.emp_no
from employees
join dept_emp using(emp_no)
join departments using(dept_no)
join dept_manager using (dept_no)
where dept_emp.to_date > now()

'''

, url)


In [122]:
query.head(5)

manager_emp_no gender         dept_name  emp_no
0          111692      M  Customer Service   10038
1          111784      M  Customer Service   10038
2          111877      M  Customer Service   10038
3          111939      M  Customer Service   10038
4          111692      F  Customer Service   10049

- Is an employee's gender independent of whether an employee works in sales or marketing? (only look at current employees)

Ho: independent
Ha: dependent

In [113]:
observed = pd.crosstab(query.gender,query.dept_name)

In [114]:
chi2,p,degf,expected = stats.chi2_contingency(observed)

In [115]:
print('Observed')
print(observed.values)
print('\nExpected')
print(expected.astype(int))
print('\n----')
print(f'chi^2 = {chi2:.4f}')
print(f'p     = {p:.4f}')

Observed
[[ 28028  49066  10028  10294  11728  85572  23488  12362  29998]
 [ 42248  73706  14846  15502  17956 127644  34696  18520  45404]]

Expected
[[ 28124  49133   9954  10323  11879  85328  23285  12358  30175]
 [ 42151  73638  14919  15472  17804 127887  34898  18523  45226]]

----
chi^2 = 10.8187
p     = 0.2122


In [140]:
if p < alpha:
    print('reject the null hypothesis')
else:
    print('fail to reject the null hypothesis, gender is independent of department names')

fail to reject the null hypothesis, gender is independent of department names


In [123]:
query.head()

manager_emp_no gender         dept_name  emp_no
0          111692      M  Customer Service   10038
1          111784      M  Customer Service   10038
2          111877      M  Customer Service   10038
3          111939      M  Customer Service   10038
4          111692      F  Customer Service   10049

In [124]:
observed = pd.crosstab(query.gender, query.manager_emp_no)

manager_emp_no  110022  110039  110085  110114  110183  110228  110303  \
gender                                                                   
F                 5864    5864    5014    5014    5147    5147   21393   
M                 8978    8978    7423    7423    7751    7751   31911   

manager_emp_no  110344  110386  110420  ...  110800  110854  111035  111133  \
gender                                  ...                                   
F                21393   21393   21393  ...    5872    5872   14999   14999   
M                31911   31911   31911  ...    8674    8674   22702   22702   

manager_emp_no  111400  111534  111692  111784  111877  111939  
gender                                                          
F                 6181    6181    7007    7007    7007    7007  
M                 9260    9260   10562   10562   10562   10562  

[2 rows x 24 columns]

In [125]:
chi2,p,degf,expected = stats.chi2_contingency(observed)

In [126]:
print('Observed')
print(observed.values)
print('\nExpected')
print(expected.astype(int))
print('\n----')
print(f'chi^2 = {chi2:.4f}')
print(f'p     = {p:.4f}')

Observed
[[ 28028  49066  10028  10294  11728  85572  23488  12362  29998]
 [ 42248  73706  14846  15502  17956 127644  34696  18520  45404]]

Expected
[[ 28124  49133   9954  10323  11879  85328  23285  12358  30175]
 [ 42151  73638  14919  15472  17804 127887  34898  18523  45226]]

----
chi^2 = 10.8187
p     = 0.2122


In [129]:
if p < alpha:
    print('reject the null hypothesis')
else:
    print('fail to reject the null hypothesis')

fail to reject the null hypothesis
